---
# tasks file for common

- name: set timezone to Europe/Moscow
  timezone:
    name: "{{ time_zone }}"
  become: yes

- block:
    - name: create a swap file
      shell: fallocate -l {{ swap_size }} {{ swap_file }}
      args:
        creates: "{{ swap_file }}"
      become: yes

    - name: set the correct permissions
      file:
        path: "{{ swap_file }}"
        owner: root
        group: root
        mode: '0600'
      become: yes

    - name: make the file a swap file
      shell: mkswap {{ swap_file }}
      when: ansible_facts.swapfree_mb == 0
      become: yes

    - name: enable the swap file
      shell: swapon {{ swap_file }}
      when: ansible_facts.swapfree_mb == 0
      become: yes

    - name: add swap file to fstab
      mount:
        name: none
        src: "{{ swap_file }}"
        fstype: swap
        opts: sw
        passno: 0
        dump: 0
        state: present
      become: yes

- name: set a hostname
  hostname:
    name: "{{ inventory_hostname }}"
  become: yes

- name: update apt cache
  apt:
     update_cache: true
  become: yes
